# Generated by Django 5.1.2 on 2024-10-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_note_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='z8d2mnnmvt7p4b0lgmiviuafhzpp80dv2c5il2be76sj8gpdn4dqz03ndcu15', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
