# Generated by Django 5.1.2 on 2024-10-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_note_slug_alter_sources_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='rnr03agrj7gxkd3d5jsi0nouff0ksifeafz4f4aw2stdjuezrjaf', max_length=255, unique=True),
        ),
    ]
