# Generated by Django 5.1.2 on 2024-10-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_remove_sources_pdf_format_check_alter_note_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='pezy5ibjqs3rv69ht68vkt7ieb60jh3u9ua5t7u61kqyeymr', max_length=255, unique=True),
        ),
    ]
