# Generated by Django 5.1.2 on 2024-10-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='yxc3fp02f3hcg3y4ughcdvn5ax5rdv7yo2z0cvyd74ml', max_length=255, unique=True),
        ),
    ]
