# Generated by Django 5.1.2 on 2024-10-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='900m1we9r9z4cx5ajaxoka8vdrcj8pzopy2k0c1eu8hx5ji', max_length=255, unique=True),
        ),
    ]
