# Generated by Django 5.1.2 on 2024-10-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_remove_sources_file_must_be_a_pdf__alter_note_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='2lgx834fk1qs7lmhntksc2m6fc1xh3peqhchmyr37i', max_length=255, unique=True),
        ),
    ]
