# Generated by Django 5.1.2 on 2024-10-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='g4c26n3vjp8zcaee32qwbqg64j76tfe8ntr39ija28', max_length=255, unique=True),
        ),
    ]
