# Generated by Django 5.1.2 on 2024-10-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0012_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='he7a8vkzuzu61vwwrufytpiteqqoz6wa', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
