# Generated by Django 5.1.2 on 2024-10-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0013_alter_note_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='r022yt11sh2l4c2tvj3o7qtn27be5hgc', max_length=255, unique=True),
        ),
    ]
