# Generated by Django 5.1.2 on 2024-10-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0014_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='e12xqx4f0bukl9tw2h6b79gdmstn16i3', max_length=255, unique=True),
        ),
    ]
