# Generated by Django 5.1.2 on 2024-10-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0015_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, default='g8r3u8zvqfs9bi9jjtybjq2gxa1lpls0', max_length=255, unique=True),
        ),
    ]
