# Generated by Django 5.1.2 on 2024-10-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0016_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
