# Generated by Django 5.1.2 on 2024-10-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0017_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
