# Generated by Django 5.1.2 on 2024-11-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0018_alter_sources_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
