# Generated by Django 5.1.2 on 2024-11-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0019_alter_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
    ]
